name: Build & Test
on: 
  push:
  workflow_dispatch: 
  workflow_call: 
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Install dependencies
        run: dotnet restore -p:TargetFramework=net${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --configuration Release --no-build --no-restore